language: erlang
otp_release:
  - 18.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
script:
  - mix test
notifications:
  recipients:
    - jquadrin@gmail.com 
